[audio]
# How many samples per second to collect
SAMPLE_RATE = 16000
MODEL_PATH = "cache/moonshine/tiny-streaming"
MODEL_ARCH = 2 #tiny streaming

[question-detection]
# For now, we do a simple trailing context of the last twenty transcripts we've heard
DEBOUNCE_SECONDS = 0.8

[remote]
url = "ws://localhost:8765/cse481/ws/pi"